// app/Componentes/traducción.js

const translations = {
    en: {
      title: "Register",
      header: "Register",
      username: "Username:",
      usernameOrEmail: "Username or Email:",
      noAccount: "Don't Have an account yet?",
      registerHere: "Sign Up Here!",
      alreadyHaveAccount: "Already have an account?",
      loginHere: "Log in Here!",
      email: "Mail Address: ",
      confirmPassword: "Confirm Password:",
      password: "Password:",
      registerButton: "Register",
      searchPlaceholder: "Search albums or artists",
      languageLabel: "Language:",
      registerSuccess: "Registration successful",
      userExists: "User already exists",
      registerError: "Error registering user",
      cart: "Cart",
      promotions: "Promotions",
      newDiscs: "New Records",
      genres: "Genres",
      sustainableSound: "Sustainable Sound",
      welcome: "Welcome to Sustainable Sound!",
      login: "Login",
      createUser: "Create User",   
      loginPageTitle: "Login",
      loginButton: "Login",
      loginSuccess: "Login successful",
      loginError: "Incorrect credentials",
      Slogan: "Immerse Yourself in the Sound of the Earth",
      SloganFoot: "Discover sustainable music with records made from recycled materials",
      SearchPlaceholder: "Search disks",
      SearchButton: "Search",
      PromotedDisks: "Promoted CDs",
      settings: "Settings",
      chooseLanguage: "Change Language to Spanish",
      Cart: "Add to Cart",
      tracklist: "Track List",
      Results: "Search Results",
      latest: "latest disks",
      Todos_los_derechos_reservados: "All rights reserved",
      Buscardiscos: "Search disks",
      cartTitle: 'Your Cart',
      cartEmpty: 'Your cart is empty.',
      product: 'Product',
      price: 'Price',
      quantity: 'Quantity',
      total: 'Total',
      actions: 'Actions',
      remove: 'Remove',
      clearCart: 'Clear Cart',
      checkout: 'Checkout',
      checkoutSuccess: 'Purchase successful!',
      logout: "Log Out"
      
    },
    es: {
      title: "Registro",
      header: "Registro",
      username: "Usuario:",
      usernameOrEmail: "Usuario o Correo:",
      noAccount: "¿No tienes una cuenta?",
      registerHere: "¡Regístrate aquí!",
      alreadyHaveAccount: "¿Ya tienes una cuenta?",
      loginHere: "¡Ingresa aquí!",
      email: "Correo Electrónico:",
      confirmPassword: "Confirme su Contraseña:",
      password: "Contraseña:",
      registerButton: "Registrar",
      searchPlaceholder: "Buscar discos o artistas",
      languageLabel: "Idioma:",
      registerSuccess: "Registro exitoso",
      userExists: "El usuario ya existe",
      registerError: "Error al registrar usuario",
      cart: "Carrito",
      promotions: "Promociones",
      newDiscs: "Discos Nuevos",
      genres: "Géneros",
      sustainableSound: "Sustainable Sound",
      welcome: "¡Bienvenido a Sustainable Sound!",
      login: "Iniciar Sesión",
      createUser: "Crear Usuario",
      loginPageTitle: "Iniciar Sesión",
      loginButton: "Iniciar Sesión",
      loginSuccess: "Inicio de sesión exitoso",
      loginError: "Credenciales incorrectas",
      Slogan: "Sumérgete en el Sonido de la Tierra",
      SloganFoot: "Descubre música sostenible con discos hechos de materiales reciclados",
      SearchPlaceholder: "Buscar discos",
      SearchButton: "Buscar",
      PromotedDisks: "Discos Promocionados",
      settings: "Configuración",
      chooseLanguage: "Cambiar el idioma a Inglés",
      Cart:"Agregar al Carrito",
      tracklist: "Lista de Temas",
      Results: "Resultados de Busqueda",
      latest: "Ultimos discos",
      Todos_los_derechos_reservados: "Todos los  derechos reservados",
      Buscardiscos: "Buscar discos",
      cartTitle: 'Tu Carrito',
      cartEmpty: 'Tu carrito está vacío.',
      product: 'Producto',
      price: 'Precio',
      quantity: 'Cantidad',
      total: 'Total',
      actions: 'Acciones',
      remove: 'Eliminar',
      clearCart: 'Vaciar Carrito',
      checkout: 'Finalizar Compra',
      checkoutSuccess: 'Compra realizada con éxito!',
      logout: "Cerrar Sesión"
    },
    // Puedes agregar más idiomas aquí
  };
  
  export default translations;
  