// app/Componentes/traducción.js

const translations = {
    en: {
      title: "Register",
      header: "Register",
      username: "Username:",
      password: "Password:",
      registerButton: "Register",
      searchPlaceholder: "Search albums or artists",
      languageLabel: "Language:",
      registerSuccess: "Registration successful",
      userExists: "User already exists",
      registerError: "Error registering user",
      cart: "Cart",
      promotions: "Promotions",
      newDiscs: "New Records",
      genres: "Genres",
      sustainableSound: "Sustainable Sound",
      welcome: "Welcome to Sustainable Sound!",
      login: "Login",
      createUser: "Create User",   
      loginPageTitle: "Login",
      loginButton: "Login",
      loginSuccess: "Login successful",
      loginError: "Incorrect credentials",   
    },
    es: {
      title: "Registro",
      header: "Registro",
      username: "Usuario:",
      password: "Contraseña:",
      registerButton: "Registrar",
      searchPlaceholder: "Buscar discos o artistas",
      languageLabel: "Idioma:",
      registerSuccess: "Registro exitoso",
      userExists: "El usuario ya existe",
      registerError: "Error al registrar usuario",
      cart: "Carrito",
      promotions: "Promociones",
      newDiscs: "Discos Nuevos",
      genres: "Géneros",
      sustainableSound: "Sustainable Sound",
      welcome: "¡Bienvenido a Sustainable Sound!",
      login: "Iniciar Sesión",
      createUser: "Crear Usuario",
      loginPageTitle: "Iniciar Sesión",
      loginButton: "Iniciar Sesión",
      loginSuccess: "Inicio de sesión exitoso",
      loginError: "Credenciales incorrectas",
    },
    // Puedes agregar más idiomas aquí
  };
  
  export default translations;
  